name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        continue-on-error: true
      
      - name: Build site
        run: |
          # 确保index.html存在
          if [ ! -f "index.html" ]; then
            echo "index.html not found, creating redirect..."
            echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;url=./shan-zhi-mei-mobile.html"></head><body>Redirecting...</body></html>' > index.html
          fi
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}